# Sample- syslock.conf
# The immutable-flag config line is optional. Default behavior is
# schg for BSD, uchg for macOS (schg is equivalent on Apple Silicon,
# where there is no single-user mode) and +i (only supported option)
# for Linux.
# immutable-flag: +i
#
# Optionally groups of pathnames can be identified with a
# group: <groups>
# line in front of them. Group names can be alphanumeric plus hyphens,
# separated by spaces.

# If the "+a" group is added alongside other groups, you can set
# and reset the append-only flag for those groups with
# syslock -g group:+a and sysunlock -g group:+a;; if groups are defined
# that are *only* alongside "+a", then ":+a" need not be explicit.
#
# Flags in front of a file path:
# + Do not recurse through subdirectories.
# - Do not lock a directory itself, just its contents.
# ! If the -s option to syslock/sysunlock is used, only lock/unlock these items.
# (This functionality is important for BSD where schg flags are used.)

# Sample file list for Linux.
group: etc configs system
/etc/cron.daily
/etc/cron.hourly
/etc/cron.monthly
/etc/cron.weekly
/etc/cron.yearly
/etc/cron.d
# there is a Linux package for doas
#/etc/doas.conf
/etc/init.d
/etc/rc0.d
/etc/rc1.d
/etc/rc2.d
/etc/rc3.d
/etc/rc4.d
/etc/rc5.d
/etc/sudoers
/etc/syslock.conf

# don't unlock unless you need to - could use schg group if uchg is default
group: fstab
/etc/fstab

# /etc rarely unlocked - could use schg group if uchg is default
group: etcrare
#/etc/hostname.* - must be specified individually, globs won't work
/etc/ipsec.conf
/etc/ipsec.d
/etc/ipsec.secrets
/etc/login.defs
/etc/network
/etc/NetworkManager
# there is a Linux package for signify-openbsd
#/etc/signify

group: etcrare ssl
/etc/ssl

group: etc configs mail system
/etc/aliases
/etc/exim4

group: etc configs ssh system
/etc/ssh

# Binaries and libraries.
group: binaries system
# omit /bin and /sbin if symlinks
#/bin
#/sbin
/usr/bin
!/usr/sbin

group: binaries libraries system
!/usr/libexec
!/usr/lib

group: binaries local
/usr/local/bin
/usr/local/sbin

group: binaries libraries local
/usr/local/lib

# Kernel.
group: binaries kernel system
!/boot

# Process account logs. Append-only for live log, rest immutable.
# Must be unlocked before rotation and relocked afterward.
# (For Proxmox, it's in /etc/cron.daily/acct script.)
group: +a acct acct-logs
/var/log/account/pacct
group: acct acct-logs
/var/account/pacct.0
/var/account/pacct.*.gz
