# Sample- syslock.conf
# The immutable-flag config line is optional. Default behavior is
# schg for BSD, uchg for macOS (schg is equivalent on Apple Silicon,
# where there is no single-user mode) and +i (only supported option)
# for Linux.
# immutable-flag: +i
#
# Optionally groups of pathnames can be identified with a
# group: <groups>
# line in front of them. Group names can be alphanumeric plus hyphens,
# separated by spaces.

# If the "+a" group is added alongside other groups, you can set
# and reset the append-only flag for those groups with
# syslock -g group:+a and sysunlock -g group:+a;; if groups are defined
# that are *only* alongside "+a", then ":+a" need not be explicit.
#
# Flags in front of a directory file path:
# + Do not recurse through subdirectories.
# - Do not lock a directory itself, just its contents.
# = Lock a directory and its file contents, but not subdirectories.

# Sample file list for Linux.
group: etc configs system
/etc/cron.daily
/etc/cron.hourly
/etc/cron.monthly
/etc/cron.weekly
/etc/cron.yearly
# Proxmox may place maintenance or subscription-related cron snippets 
# in /etc/cron.d (e.g., pve-debian-advisor). Lock the directory to 
# ensure these services aren't modified or disabled by mistake.
/etc/cron.d
/etc/init.d
/etc/rc0.d
/etc/rc1.d
/etc/rc2.d
/etc/rc3.d
/etc/rc4.d
/etc/rc5.d
/etc/sudoers
/etc/syslock.conf
# Proxmox:
#/etc/pve excluded, it's a FUSE mount.
#/etc/lvm excluded, frequently rewritten during VM disk operations.

# doas.conf - there is a Linux package
#group: etc doas configs system
# there is a Linux package for doas
#/etc/doas.conf

# don't unlock unless you need to
group: fstab configs system
/etc/fstab

# /etc rarely unlocked
group: etcrare configs system
/etc/default/grub
/etc/default/networking
# Proxmox: Not present if using single node
#/etc/default/pve-cluster
/etc/default/ssh
/etc/hosts
/etc/ipsec.conf
/etc/ipsec.d
/etc/ipsec.secrets
/etc/login.defs
/etc/modules
# On Proxmox, /etc/network must be unlocked for interface
# changes from the GUI, which requires the ability to create
# /etc/network/interfaces.new and move it into place by
# pvenetcommit (if it fails, networking might fail to come
# up or come up with old config); this directory must also be
# unlocked if using pve-network-interface-pinning.
/etc/network
/etc/NetworkManager
/etc/pam.d
/etc/sysctl.conf
# Might be a good idea to touch /etc/sysctl.conf and lock if
# it doesn't exist--or otherwise monitor for the file being
# created.
/etc/sysctl.d

group: etc configs mail system
/etc/aliases
/etc/exim4

# reportnew
#group: etc configs reportnew
#/etc/reportnew/reportnew.conf

# rsync
#group: etc configs rsync
#/etc/rsync/rsync.conf

# signify - there is a Linux package, signify-openbsd
#group: etcrare signify system
#/etc/signify

# sigtree
#group: etc configs sigtree
#/etc/<hostname>.sigtree.conf

group: etc ssh system
/etc/ssh

group: etcrare ssl system
/etc/ssl

# Binaries and libraries.
group: binaries system
# omit /bin and /sbin if symlinks
#/bin
#/sbin
/usr/bin
/usr/sbin

group: binaries libraries system
/usr/libexec
/usr/lib

group: binaries local
/usr/local/bin
/usr/local/sbin

group: binaries libraries local
/usr/local/lib

# Kernel.
group: binaries kernel system
/boot
# For Proxmox: allows unlocking just "grub" group on
# reboots to allow writing grubenv and grub.cfg in /boot/grub.
#group: binaries boot kernel system
# lock /boot and file contents but not subdirectories
#=/boot
# lock /boot/efi and /boot/pve subdirectories recursively
#/boot/efi
#/boot/pve
#group: binaries boot grub system
# lock /boot/grub recursively
#/boot/grub

# Process account logs. Append-only for live log, rest immutable.
# Must be unlocked before rotation and relocked afterward.
# (For Proxmox, it's in /etc/cron.daily/acct script.)
group: +a acct acct-logs
/var/log/account/pacct
group: acct acct-logs
/var/account/pacct.0
/var/account/pacct.*.gz
